from datetime import date
import os

from sqlalchemy import select
from sqlalchemy.orm import Session
from .. import models
from ..auth.security import hash_password
from .ledger import log_action, recalculate_after_transaction

def seed_database(db: Session) -> None:
    # Seed operational accounts only when missing. Existing credentials are never reset.
    admin = db.scalar(select(models.User).where(models.User.email == "admin@brb.com"))
    if not admin:
        admin = models.User(
            name="Balam Bar Baran Admin",
            username="admin",
            email="admin@brb.com",
            password_hash=hash_password("admin123"),
            role="Admin",
        )
        db.add(admin)
        db.flush()

    default_user = db.scalar(select(models.User).where(models.User.email == "ahsan@sky.com"))
    if not default_user:
        default_user = models.User(
            name="Ahsan",
            username="ahsan",
            email="ahsan@sky.com",
            password_hash=hash_password("Qur78Ahs@@"),
            role="Admin",
        )
        db.add(default_user)
        db.flush()
    elif not default_user.username:
        default_user.username = "ahsan"
        db.flush()

    # Check if accountant already exists
    accountant = db.scalar(select(models.User).where(models.User.email == "accountant@skybanking.local"))
    if not accountant:
        accountant = models.User(
            name="General Accountant",
            email="accountant@skybanking.local",
            password_hash=hash_password("1234"),
            role="Accountant",
        )
        db.add(accountant)
        db.flush()

    # Check if settings exist
    settings = db.scalar(select(models.Settings))
    if not settings:
        settings = models.Settings(
            company_name="Sky Ariana & Balam Bar Baran",
            address="Kabul, Afghanistan",
            phone="+93 799 123 456",
            email="finance@brb.com",
            receipt_footer="Official receipt generated by Sky Ariana & Balam Bar Baran.",
            default_currency="USD",
        )
        db.add(settings)
        db.flush()

    # Sample Customers (Idempotent check)
    shir_ahmad = db.scalar(select(models.Customer).where(models.Customer.name == "شیر احمد"))
    if not shir_ahmad:
        shir_ahmad = models.Customer(name="شیر احمد", phone="+93 700 111 222", notes="Primary hawala customer")
        db.add(shir_ahmad)

    ariana = db.scalar(select(models.Customer).where(models.Customer.name == "Ariana Balam Baran"))
    if not ariana:
        ariana = models.Customer(name="Ariana Balam Baran", phone="+93 700 333 444", notes="Transport statement customer")
        db.add(ariana)
        
    db.flush()

    # Sample Bank Accounts (Idempotent check)
    banks = []
    for bank_info in [
        {"bank_name": "AIB Bank", "account_name": "Booking Account", "account_number": "1102-8890-USD", "currency": "USD", "opening_balance": 25000},
        {"bank_name": "Ghazanfar Bank", "account_name": "Company Account", "account_number": "4471-2200-AFN", "currency": "Afghani", "opening_balance": 880000},
        {"bank_name": "Hawala Office", "account_name": "Dubai Hawala Desk", "account_number": "DXB-HWL-443", "currency": "Dirham", "opening_balance": 12000},
    ]:
        existing_bank = db.scalar(select(models.BankAccount).where(models.BankAccount.account_number == bank_info["account_number"]))
        if not existing_bank:
            existing_bank = models.BankAccount(
                bank_name=bank_info["bank_name"],
                account_name=bank_info["account_name"],
                account_number=bank_info["account_number"],
                currency=bank_info["currency"],
                opening_balance=bank_info["opening_balance"],
                current_balance=bank_info["opening_balance"]
            )
            db.add(existing_bank)
            db.flush()
        banks.append(existing_bank)

    # Demo transactions are opt-in so deleted archive rows are never recreated
    # automatically on backend restart.
    seed_demo_data = os.getenv("SEED_DEMO_DATA", "").strip().lower() in {"1", "true", "yes", "on"}

    # Sample Transactions based on Balam Bar Baran structure (Idempotent check)
    transactions_to_add = []
    sample_txs_data = [
        {
            "receipt_no": "BB-2026-0001",
            "date": date.today(),
            "type": "Received",
            "customer_id": shir_ahmad.id,
            "company_name": "شیر احمد لیتد",
            "subject": "Paid bank statement record",
            "amount": 5000,
            "currency": "USD",
            "equivalent_amount": 360000,
            "equivalent_currency": "Afghani",
            "payment_method": "Bank Transfer",
            "bank_account_id": banks[0].id,
            "receiver_name": "Finance Department",
            "description": "Deposit received against transport statement from شیر احمد.",
            "status": "Completed",
            "created_by": admin.id,
        },
        {
            "receipt_no": "BB-2026-0002",
            "date": date.today(),
            "type": "Paid",
            "customer_id": shir_ahmad.id,
            "company_name": "شیر احمد لیتد",
            "subject": "Hawala settlement",
            "amount": 150000000,
            "currency": "Toman",
            "equivalent_amount": 2500,
            "equivalent_currency": "USD",
            "payment_method": "Hawala",
            "bank_account_id": banks[2].id,
            "receiver_name": "Dubai Office Cashier",
            "description": "Settlement of transport balance.",
            "status": "Completed",
            "created_by": admin.id,
        },
        {
            "receipt_no": "BB-2026-0003",
            "date": date.today(),
            "type": "Received",
            "customer_id": ariana.id,
            "company_name": "Balam Bar Baran Int",
            "subject": "Cash receipt collection",
            "amount": 4250,
            "currency": "USD",
            "equivalent_amount": 306000,
            "equivalent_currency": "Afghani",
            "payment_method": "Cash",
            "receiver_name": "Kabul Office",
            "description": "Deposit received against transport statement.",
            "status": "Completed",
            "created_by": admin.id,
        }
    ] if seed_demo_data else []

    for tx_data in sample_txs_data:
        existing_tx = db.scalar(select(models.Transaction).where(models.Transaction.receipt_no == tx_data["receipt_no"]))
        if not existing_tx:
            tx = models.Transaction(**tx_data)
            db.add(tx)
            transactions_to_add.append(tx)
            
    db.flush()

    for transaction in transactions_to_add:
        recalculate_after_transaction(db, transaction)

    if transactions_to_add:
        log_action(db, admin.id, "seed", "database", None, "Seeded Sky Ariana & Balam Bar Baran demo transaction records.")
    db.commit()
